version: 1
disable_existing_loggers: true

formatters:
  console:
    class: colorlog.ColoredFormatter
    format: "%(log_color)s %(levelname)-8s %(asctime)s.%(msecs)03d | %(message)s (%(filename)s:%(lineno)s)"
    datefmt: "%Y-%m-%d %H:%M:%S"

  console_without_file_origin:
    class: colorlog.ColoredFormatter
    format: "%(log_color)s %(levelname)-8s %(asctime)s.%(msecs)03d | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  file:
    format: "%(levelname)-8s %(asctime)s.%(msecs)03d | %(message)s (%(filename)s:%(lineno)s)"
    datefmt: "%Y-%m-%d %H:%M:%S"

#filters:
#  debug_filter:
#    (): __main__.DebugFilter
#  error_filter:
#    (): __main__.ErrorFilter

handlers:
  console_debug:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console
    stream: ext://sys.stdout
  #    filters: [error_filter]

  console_error:
    class: logging.StreamHandler
    level: ERROR
    formatter: console
    stream: ext://sys.stdout
  #    filters: [error_filter]

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: file
    filename: ../logs/debug.log
    maxBytes: 2097152 # 2MB = 2 * 1024 * 1024
    backupCount: 10

  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console_without_file_origin
    stream: ext://sys.stdout
    #    filters: [error_filter]

loggers:
  sampleLogger:
    level: DEBUG
    handlers: [console_debug, file_handler]
    propagate: no

  connsole_output:
    level: DEBUG
    handlers: [console_handler, file_handler]
    propagate: no

root:
  level: DEBUG
  handlers: [console_debug, file_handler]
  propagate: no
